### ISSUE TITLE
could processes sort by msg queue length? thanks

### ISSUE THREAD

**Issue by njnuwjq** [zhongwencool/observer_cli#2]
||Pos|Pid         |     Memory| Name or Initial Call          | Reductions|**# Msg Queue** |Current Function                               |
|1  |<0.1558.23> |    2546632| erlang:apply/2                |      47415|0         |shell:get_command1/5                           |
|2  |<0.7074.23> |    1945520| erlang:apply/2                |     141245|0         |shell:eval_loop/3                              |
|3  |<0.17146.14>|    1115320| lager_event                   |  127875168|0         |gen_event:fetch_msg/5                          |

**Comment by zhongwencool** [comment]
@njnuwjq :)
