### ISSUE TITLE
Question around process list

### ISSUE THREAD

**Issue by sb8244** [zhongwencool/observer_cli#29]
Awesome work on this library! Very useful and well executed in my short time with it.

I may be missing something so wanted to ask. Is it possible to page/scroll through the process list to see additional processes, beyond what will fit in the buffer?

Cheers.

**Comment by zhongwencool** [comment]
Thank you for  your advice, I will add this page in `1.3.0`

**Comment by sb8244** [comment]
Thanks @zhongwencool . I will look for ways to contribute to this library. I think it's *really* cool

**Comment by zhongwencool** [comment]
Support `F/B` (forward/backward) or `pd/pu` (PageDown/PageUp) to see the process list on 1.3.0
