### ISSUE TITLE
Bad arithmetic error

### ISSUE THREAD

**Issue by sb8244** [zhongwencool/observer_cli#36]
I get this when I sort by mq. I haven't dug into why it occurs yet. I have not seen it on any other sort options.

```
15:16:55.374 [error] Error in process #PID<6859.16834.4700> on node :"redact@100.117.192.22" with exit value:
{:badarith,
 [{:observer_cli_lib, :byte_to_str, 1,
   [file: '/app/deps/observer_cli/src/observer_cli_lib.erl', line: 100]},
  {:observer_cli, :"-render_process_rank/4-fun-4-", 4,
   [file: '/app/deps/observer_cli/src/observer_cli.erl', line: 349]},
  {:lists, :foldr, 3, [file: 'lists.erl', line: 1276]},
  {:observer_cli, :render_process_rank, 4,
   [file: '/app/deps/observer_cli/src/observer_cli.erl', line: 341]},
  {:observer_cli, :redraw, 6,
   [file: '/app/deps/observer_cli/src/observer_cli.erl', line: 112]}]}
```

**Comment by zhongwencool** [comment]
sometime the pid has already die and the byte return a `:die` atom
then `:die/(1024*1024*1024)*1000` throws bad arithmetic error.
https://github.com/zhongwencool/observer_cli/blob/1.2.2/src/observer_cli_lib.erl#L100

I have rewrite this transform function in 1.3.0, so  the problem has already fixed it >= 1.3.0
the `observer_cli_lib:byte_to_str/1` has already been remove.

---

It is highly recommended to upgrade to 1.3.1.
Support `F/B` (forward/backward) or` pd/pu` (PageDown/PageUp) to see the process list.
and lots of small improvement.
