### ISSUE TITLE
Keyboard does not work with Linux KDE 5

### ISSUE THREAD

**Issue by JohnBat26** [zhongwencool/observer_cli#39]
Hello
I'm trying to run observer_cli in KDE5 konsole.
Program starts normally, but it doesn't react at pressing any keys :(.
Why ?

**Comment by JohnBat26** [comment]
Hi. Thanks for quick answer!
```
3> io:get_line("whatever:").   
whatever:A
"A\n"
4> io:get_line("whatever:").
whatever:D
"D\n"
5> 
```
And I start observer_cli how:
```
 ./observer_cli host cookie
```
Thus I don't use iex or erl.

**Comment by zhongwencool** [comment]
All seems normal...
1. Please try it in local shell mode to see if it's normal.
```erlang
%% rebar3 project
rebar3 shell
1> observer_cli:start().
%% mix project
iex -S mix
iex(1)> :observer_cli.start
```
2. If the above works fine, then try remote mode to see if it's normal.
start a master node by:
```erlang
erl -name test@127.0.0.1 -setcookie test
```
```erlang
%% rebar3 project
rebar3 shell --name 'observer_cli@127.0.0.1'
1> observer_cli:start('test@127.0.0.1', 'test').
%% mix project
iex --name "observer_cli@127.0.0.1" -S mix
iex(1)> :observer_cli.start(:'test@127.0.0.1', :'test')
```
3. If all works fine, the try the last one:
start a master node by:
```erlang
erl -name test@127.0.0.1 -setcookie test
./observer_cli test@127.0.0.1 test
```

**Comment by JohnBat26** [comment]
Yes. It's clear for me now. I need press Enter atfer select target tab.
Thanks for awesome tool! :+1:
