### ISSUE TITLE
Please, upgrade to recon 2.3.1

### ISSUE THREAD

**Issue by sergej-klimenko** [zhongwencool/observer_cli#4]
Please, upgrade to recon 2.3.1, 
mostly because of this fix 
(https://github.com/ferd/recon/commit/2e6facd534c58fc8e232e681ba7ccb8b137cad0b) Avoid divide by zero in scheduler_usage/1 on lightly loaded systems.

**Comment by zhongwencool** [comment]
Thanks,I will update this tomorrow.👏

**Comment by zhongwencool** [comment]
https://github.com/ferd/recon/issues/43
recon 2.3.1 on hex can't compile in elixir 1.2.5 
so do't upgrade right now.

**Comment by developerworks** [comment]
@zhongwencool recon 2.3.1 could be compiled with elixir `1.2.6` and `1.3.0`

**Comment by zhongwencool** [comment]
1.0.7   done :) 
also support 
```erlang
recon:inet_count/2 
recon:inet_windows/3
```
Better UI @developerworks @sergej-klimenko
