### ISSUE TITLE
How move line cursor ?

### ISSUE THREAD

**Issue by JohnBat26** [zhongwencool/observer_cli#40]
Hello again :)
May I move green cursor among process list ?

**Comment by zhongwencool** [comment]
<img src="https://user-images.githubusercontent.com/3116225/39091211-55554414-4622-11e8-8b28-bd3b5c7e17a6.jpg" width="90%" alt="Home"></img>

if you want to move to `<0.38.0>` pid .
```
press 6  -> press enter
```
pd/pu      to pagedown/pageup

**Comment by JohnBat26** [comment]
Thanks! ;)
