### ISSUE TITLE
Ets view incorrectly displays memory usage

### ISSUE THREAD

**Issue by d2km** [zhongwencool/observer_cli#47]
Hi, thanks for the great tool!

We found an issue with `Ets` view (the one activated with `E`) incorrectly displaying memory size of the tables. It would seem that the value displayed corresponds to the value in `{memory, X}` tuple returned by `ets:info/1`. However, that value is [in machine words](http://erlang.org/doc/man/ets.html#info-1), not in bytes.  `Home` view (activated with `H`) displays the correct size.

**Comment by zhongwencool** [comment]
Good Catch!
I fixed on `1.4.1`.
