### ISSUE TITLE
Manually adding dependency :recon necessary for mix

### ISSUE THREAD

**Issue by chrta** [zhongwencool/observer_cli#6]
I had to add this to my Mixfile to make it work:
~~~
defp deps do
    [
      {:observer_cli, "~> 1.0.8"},
      {:recon, "~> 2.3.2"}
    ]
  end
~~~

It seems that the recon dependency is properly defined in observer_cli version 1.0.8 for mix.

Otherwise i get the following error when starting the application:
~~~
** (Mix) Could not start application recon: could not find application file: recon.app
~~~

**Comment by zhongwencool** [comment]
Thanks, it failed by mix can't fetch recon deps.
I will find another way to make it work later. 
:)

**Comment by zhongwencool** [comment]
@chrta   
`{:obsever_cli, "~>1.0.9"} `
will fix this issue. (Don't need manually add `recon` deps.
