### ISSUE TITLE
Support Nerves by no longer depending on hard-coded OTP_VERSION file location

### ISSUE THREAD

**Issue by Qqwy** [zhongwencool/observer_cli#61]
I tried to add `observer_cli` to Nerves.
However, upon attempting to start it, it will crash with the following error:

```
00:01:22.567 [error] Process #PID<0.1234.0> on node :"my@device.name" raised an exception
** (MatchError) no match of right hand side value: {:error, :enoent}
    (observer_cli) src/observer_cli.erl:607: :observer_cli.get_stable_system_info/0
    (observer_cli) src/observer_cli.erl:123: :observer_cli.render_worker/3
```

Digging into the code, it seems that `observer_cli` is using a function called `get_stable_system_info` (which seems to only be used to display the full version (both major and minor) of OTP that [under the covers](https://github.com/zhongwencool/observer_cli/blob/03bd5a8fe6c468e2e1677336301b545d2f023961/src/observer_cli.erl#L604) attempts to read a file located at e.g. `/srv/erlang/releases/22/OTP_VERSION`

This location does not exist on Nerves  (and actually the whole `22` folder) . The `OTP_VERSION` file can therefore not be read.

----

My suggestion would be to fallback to just set `Version = erlang:system_info(otp_release)` in case the file is not found, rather than crashing violently.

**Comment by zhongwencool** [comment]
@Qqwy Thank you for reporting, I have fixed it as your advice.
Please try `1.5.2`.

**Comment by Qqwy** [comment]
Thank you for the update! Version `1.5.2` runs like a charm on my Raspberry Pi 3.

Much appreciated! :green_heart:
