### ISSUE TITLE
Row numbers in plugins?

### ISSUE THREAD

**Issue by ioolkos** [zhongwencool/observer_cli#66]
Is it possible to add row numbers in plugins, switching to a detail view when a row is selected?
Thank you!

**Comment by zhongwencool** [comment]
sorry, We don't support this yet...

**Comment by ioolkos** [comment]
Okay, thank you for your work on observer_cli!

**Comment by ioolkos** [comment]
@zhongwencool I forgot to ask: is this something at all that you eventually plan to add? what is your estimation on effort/complexity for adding this?
Thanks.
