### ISSUE TITLE
How to get full names of processes within Home tab?

### ISSUE THREAD

**Issue by progsmile** [zhongwencool/observer_cli#67]
Hi, thank you for the library!
Is there way to fit `Name or Initial Call` column, so it shows full name of process?
Thanks!

![image](https://user-images.githubusercontent.com/6272773/81554531-a40ad080-938f-11ea-8531-39170bf35a95.png)

**Comment by zhongwencool** [comment]
Then the Name column's width is fixed,
If you want to get more information about 
![image](https://user-images.githubusercontent.com/3116225/81559354-d33a3580-93c1-11ea-98da-2822e7d66932.png)
Press 26 -> then `Enter`

If this is not enough your can use  `:sys.get_state(<0.2238.0>`
or `:erlang.process_info(<0.2238.0>`.

**Comment by progsmile** [comment]
oh, ok, thanks
