### ISSUE TITLE
Observer_cli startup crash on OTP 23

### ISSUE THREAD

**Issue by SoniCoder** [zhongwencool/observer_cli#71]
This is happening with OTP 23.1.1
`
=ERROR REPORT==== 21-Oct-2020::13:00:05.140642 ===
Error in process <9621.159.12> on node butler_server@localhost with exit value:
{badarg,[{erlang,element,[2,false],[]},
         {recon_alloc,container_value,4,
                      [{file,"src/recon_alloc.erl"},{line,699}]},
         {recon_alloc,container_size,3,
                      [{file,"src/recon_alloc.erl"},{line,671}]},
         {lists,map,2,[{file,"lists.erl"},{line,1243}]},
         {recon_alloc,memory,2,[{file,"src/recon_alloc.erl"},{line,208}]},
         {observer_cli,get_change_system_info,0,
                       [{file,"src/observer_cli.erl"},{line,616}]},
         {observer_cli,redraw_running,7,
                       [{file,"src/observer_cli.erl"},{line,150}]}]}`

**Comment by zhongwencool** [comment]
@SoniCoder plz upgrade observer to 1.5.4 
and recon 2.5.1

**Comment by SoniCoder** [comment]
Thanks it is resolved now
