### ISSUE TITLE
Windows is broken

### ISSUE THREAD

**Issue by menih** [zhongwencool/observer_cli#75]
@zhongwencool - With SHA 7f80ae49570612b3732094b76494c0fbb073aa2b , running on Windows is broken as ps is not available. Suggest to check platform and run it conditionally.

**Comment by zhongwencool** [comment]
Thanks for this report!
fixed by https://github.com/zhongwencool/observer_cli/pull/76

**Comment by menih** [comment]
Thanks! Confirming fixed.
