### ISSUE TITLE
Observer_cli startup crash on OTP 22.2 on Solaris 11.3 (sparc)

### ISSUE THREAD

**Issue by rareman99** [zhongwencool/observer_cli#77]

**Comment by rareman99** [comment]
after start obsever_cli error as below
2021-08-17T15:07:30.099625+07:00 error: Error in process <0.131.0> with exit value:, {undef,[{recon,info,[undefined],[]},{observer_cli_process,render_worker,6,[{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli-master/src/observer_cli_process.erl"},{line,34}]}]}

**Comment by rareman99** [comment]
another error as below.
4> observer_cli:start().
=ERROR REPORT==== 18-Aug-2021::14:00:31.304407 ===
Error in process <0.235.0> with exit value:
{{case_clause,["\t[","-u","userlist","]","[","-U","userlist","]","[","-G",
               "grouplist","]"]},
 [{observer_cli,render_system_line,2,
                [{file,"/root/.cache/rebar3/lib/observer_cli/src/observer_cli.erl"},
                 {line,225}]},
  {observer_cli,redraw_running,8,
                [{file,"/root/.cache/rebar3/lib/observer_cli/src/observer_cli.erl"},
                 {line,194}]}]}
=ERROR REPORT==== 18-Aug-2021::14:00:44.223433 ===
Error in process <0.236.0> with exit value:
{badarg,[{erlang,process_info,
                 [undefined,[registered_name,dictionary,group_leader,status]],
                 []},
         {recon,proc_info,2,
                [{file,"/root/.cache/rebar3/lib/recon/src/recon.erl"},
                 {line,236}]},
         {recon,info_type,3,
                [{file,"/root/.cache/rebar3/lib/recon/src/recon.erl"},
                 {line,224}]},
         {recon,'-info/1-lc$^0/1-0-',2,
                [{file,"/root/.cache/rebar3/lib/recon/src/recon.erl"},
                 {line,181}]},
         {observer_cli_process,render_worker,6,
                               [{file,"/root/.cache/rebar3/lib/observer_cli/src/observer_cli_process.erl"},
                                {line,35}]}]}

**Comment by zhongwencool** [comment]
@rareman99 please try master
https://github.com/zhongwencool/observer_cli/commit/49bec7ec77f36f93fe464c96d23e26f3ddf70cc8

the first problem is undef, you should run rebar3 compile first.
```erlang
rebar3  compile
===> Verifying dependencies...
===> Fetching recon v2.5.1
===> Analyzing applications...
===> Compiling recon
===> Analyzing applications...
===> Compiling observer_cli
```

**Comment by rareman99** [comment]
Hi  @zhongwencool 
thanks for help here below .
rebar3 compile
===> Failed to update package rebar3_format from repo hexpm
===> Errors loading plugin rebar3_format. Run rebar3 with DEBUG=1 set to see errors.
===> Failed to update package erlfmt from repo hexpm
===> Errors loading plugin erlfmt. Run rebar3 with DEBUG=1 set to see errors.
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling observer_cli

It look like problem on rebar.config I tried a lots but not success  please see below (rebar.config).
cat rebar.config
{erl_opts, [{src_dirs, ["src", "test"]},
            warn_unused_vars,
            warn_export_all,
            warn_shadow_vars,
            warn_unused_import,
            warn_unused_function,
            warn_bif_clash,
            warn_unused_record,
            warn_deprecated_function,
            warn_obsolete_guard,
            strict_validation,
            warn_export_vars,
            warn_exported_vars,
            warn_missing_spec,
            warn_untyped_record, debug_info]}.
{deps_dir, "recon"}.
%%{deps, [recon]}.
{deps, [observer_cli]}.

{escript_main_app, observer_cli}.
{escript_emu_args, "%%! -escript main observer_cli_escriptize -hidden +sbtu +A0 -elixir ansi_enabled true\n"}.
{escript_incl_apps, [recon]}.

{dialyzer_opts, [{warnings, [unmatched_returns, error_handling, race_conditions, behaviours]}]}.
{edoc_opts, [{report_missing_types, true}, {source_path, ["src"]}, {report_missing_types, true}, {todo, true}, {packages, false}, {subpackages, false}]}.
{xref_checks, [undefined_function_calls]}.
{cover_enabled, true}.
{post_hooks, [{"(linux|darwin|solaris)", edoc, "escript doc/docsite.erl"}]}.

{profiles, [
  {inet6, [
    {escript_emu_args, "%%! -escript main observer_cli_escriptize -hidden -proto_dist inet6_tcp +sbtu +A0 -elixir ansi_enabled true\n"}
  ]}
]}.

{project_plugins, [rebar3_format, erlfmt]}.
{format, [
  {files, ["src/*.erl", "include/*.hrl"]},
  {formatter, erlfmt_formatter}, %% The erlfmt formatter interface.
  {options, #{print_width => 100, ignore_pragma => true}} %% ...or no options at all.
]}.
%% rebar.config
%%{deps, [observer_cli]}.

**Comment by zhongwencool** [comment]
The log shows that you can't download rebar3_format erlfmt from repo hexpm. 
make sure you can visit hexpm.

PS: If you have already download recon the right way.
just delete `{project_plugins, [rebar3_format, erlfmt]}.` is ok.

why use 
```erlang
%% directory in '<base_dir>/<profile>/' where deps go
{deps_dir, "recon"}.
```

you better download recon by rebar3.

**Comment by rareman99** [comment]
Hi
why use

%% directory in '<base_dir>/<profile>/' where deps go
{deps_dir, "recon"}.

Cause of can't compile (observer_cli).
rebar3 compile
===> Failed to update package rebar3_format from repo hexpm
===> Errors loading plugin rebar3_format. Run rebar3 with DEBUG=1 set to see errors.
===> Failed to update package erlfmt from repo hexpm
===> Errors loading plugin erlfmt. Run rebar3 with DEBUG=1 set to see errors.
===> Verifying dependencies...
===> Failed to update package recon from repo hexpm
===> Package not found in any repo: recon
 cat rebar.config
{erl_opts, [{src_dirs, ["src", "test"]},
            warn_unused_vars,
            warn_export_all,
            warn_shadow_vars,
            warn_unused_import,
            warn_unused_function,
            warn_bif_clash,
            warn_unused_record,
            warn_deprecated_function,
            warn_obsolete_guard,
            strict_validation,
            warn_export_vars,
            warn_exported_vars,
            warn_missing_spec,
            warn_untyped_record, debug_info]}.
{deps_dir, "deps"}.
{deps, [recon]}.
{deps, [observer_cli]}.

{escript_main_app, observer_cli}.
{escript_emu_args, "%%! -escript main observer_cli_escriptize -hidden +sbtu +A0 -elixir ansi_enabled true\n"}.
{escript_incl_apps, [recon]}.

{dialyzer_opts, [{warnings, [unmatched_returns, error_handling, race_conditions, behaviours]}]}.
{edoc_opts, [{report_missing_types, true}, {source_path, ["src"]}, {report_missing_types, true}, {todo, true}, {packages, false}, {subpackages, false}]}.
{xref_checks, [undefined_function_calls]}.
{cover_enabled, true}.
{post_hooks, [{"(linux|darwin|solaris)", edoc, "escript doc/docsite.erl"}]}.

{profiles, [
  {inet6, [
    {escript_emu_args, "%%! -escript main observer_cli_escriptize -hidden -proto_dist inet6_tcp +sbtu +A0 -elixir ansi_enabled true\n"}
  ]}
]}.

{project_plugins, [rebar3_format, erlfmt]}.
{format, [
  {files, ["src/*.erl", "include/*.hrl"]},
  {formatter, erlfmt_formatter}, %% The erlfmt formatter interface.
  {options, #{print_width => 100, ignore_pragma => true}} %% ...or no options at all.
]}.

I'm newbie for erlang then I just tried to enable/disable in the rebar.config

you better download recon by rebar3.

Where to put recon? this is main problem I tried to put recon many places look like didn't work.
P.S (server can't to the internet)

**Comment by rareman99** [comment]
Hi 
I think i'm done for compile but still not success tried to switch between recon 2.5.2 and 2.5.1 still got error.

 # rebar3 compile
===> Fetching rebar3_format v1.0.1
===> Fetching katana_code v1.1.1
===> Analyzing applications...
===> Compiling katana_code
===> Compiling rebar3_format
Not formatting the formatter. We're not on the regular compiling cycle
===> Fetching erlfmt v1.0.0
===> Analyzing applications...
===> Compiling erlfmt
===> Verifying dependencies...
===> Fetching recon v2.5.2
===> Analyzing applications...
===> Compiling recon
===> Analyzing applications...
===> Compiling observer_cli
-
 rebar3 shell
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling observer_cli
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1]

Eshell V10.6  (abort with ^G)
1> l(recon).
{module,recon}
2> l(observer_cli).
{module,observer_cli}
3> observer_cli:start().
=ERROR REPORT==== 19-Aug-2021::11:14:40.897535 ===
Error in process <0.179.0> with exit value:
{{case_clause,["\t[","-u","userlist","]","[","-U","userlist","]","[","-G",
               "grouplist","]"]},
 [{observer_cli,render_system_line,2,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/src/observer_cli.erl"},
                 {line,225}]},
  {observer_cli,redraw_running,8,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/src/observer_cli.erl"},
                 {line,194}]}]}
=ERROR REPORT==== 19-Aug-2021::11:14:43.035233 ===
Error in process <0.180.0> with exit value:
{badarg,[{erlang,process_info,
                 [undefined,[registered_name,dictionary,group_leader,status]],
                 []},
         {recon,proc_info,2,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/_build/default/deps/recon/src/recon.erl"},
                 {line,236}]},
         {recon,info_type,3,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/_build/default/deps/recon/src/recon.erl"},
                 {line,224}]},
         {recon,'-info/1-lc$^0/1-0-',2,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/_build/default/deps/recon/src/recon.erl"},
                 {line,181}]},
         {observer_cli_process,render_worker,6,
                               [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/src/observer_cli_process.erl"},
                                {line,35}]}]}
=
 rebar3 clean
===> Verifying dependencies...
===> Upgrading recon v2.5.1
===> Cleaning out observer_cli...
rebar3 compile
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling recon
===> Analyzing applications...
===> Compiling observer_cli
rebar3 shell
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling observer_cli
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1]

Eshell V10.6  (abort with ^G)
1> observer_cli:start().
=ERROR REPORT==== 19-Aug-2021::11:28:28.179409 ===
Error in process <0.177.0> with exit value:
{{case_clause,["\t[","-u","userlist","]","[","-U","userlist","]","[","-G",
               "grouplist","]"]},
 [{observer_cli,render_system_line,2,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/src/observer_cli.erl"},
                 {line,225}]},
  {observer_cli,redraw_running,8,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/src/observer_cli.erl"},
                 {line,194}]}]}
=ERROR REPORT==== 19-Aug-2021::11:28:29.974835 ===
Error in process <0.178.0> with exit value:
{badarg,[{erlang,process_info,
                 [undefined,[registered_name,dictionary,group_leader,status]],
                 []},
         {recon,proc_info,2,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/_build/default/deps/recon/src/recon.erl"},
                 {line,235}]},
         {recon,info_type,3,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/_build/default/deps/recon/src/recon.erl"},
                 {line,223}]},
         {recon,'-info/1-lc$^0/1-0-',2,
                [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/_build/default/deps/recon/src/recon.erl"},
                 {line,181}]},
         {observer_cli_process,render_worker,6,
                               [{file,"/opt/erlang/22.2/lib/erlang/lib/observer_cli/src/observer_cli_process.erl"},
                                {line,35}]}]}

**Comment by zhongwencool** [comment]
use the master observer_cli.
or try to change observer_cli.erl

like this：
https://github.com/zhongwencool/observer_cli/commit/49bec7ec77f36f93fe464c96d23e26f3ddf70cc8

**Comment by rareman99** [comment]
done. I stuck this for 2-3 month. 
thanks a lots @zhongwencool  👍 
💯 
:)

![image](https://user-images.githubusercontent.com/56287666/130017135-1cfdde57-b027-4d41-baaa-a09d115f96aa.png)
