### ISSUE TITLE
Jump to process by pid

### ISSUE THREAD

**Issue by karlseguin** [zhongwencool/observer_cli#85]
If I know the pid of a process, is there any way for me to jump directly to it? Without having to search through the list? I was thinking entering something like <#.#.#> and hitting enter?

(btw, we find this project super useful, thanks!)

**Comment by zhongwencool** [comment]
support in 1.8.0
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/4b5ec7c7-a2a6-4c59-8d6d-80bdc55ab877">
