### ISSUE TITLE
Unable to connect remote ejabberd server

### ISSUE THREAD

**Issue by itty-nikhil-ps** [zhongwencool/observer_cli#91]
erl -sname `monitor@localhost`
    observer_cli:start('ejabberd@nikhil5', 'actualcookiedata').

On the remote machine, the ejabberd server is running with node name ejabberd@nikhil5. On the same remote machine while running above command, the process monitor tool gives the following error-

    badrpc,{'EXIT',{undef,[{observer_cli,start,[1500],[]},
                        {rpc,'-handle_call_call/6-fun-0-',5,
                             [{file,"rpc.erl"},{line,197}]}]}}}

Any suggestions/ideas why this is happening? Machine runs CentOS, and ejabberd-18.01, if that information is useful.

**Comment by zhongwencool** [comment]
:exclamation: **ensure observer_cli application been loaded on target node.**

you should use  escript way.
#### Escriptize
1. cd path/to/observer_cli/
2. `rebar3 escriptize` to generate an escript executable containing the project's and its dependencies' BEAM files.
    Place script(`_build/default/bin/observer_cli`) anywhere in your path and use `observer_cli` command.
3. `observer_cli TARGETNODE [TARGETCOOKIE REFRESHMS]` to monitor remote node.
