### ISSUE TITLE
output reports as serialized data

### ISSUE THREAD

**Issue by RichMorin** [zhongwencool/observer_cli#97]
Observer CLI's reports use formatted ASCII and terminal control. Parsing this is certainly possible, but it would be far nicer (less hassle and possible error) if the reports could be made available in a serialized data format (e.g., Erlang Terms, GraphQL, JSON). Could this be added as an option?

**Comment by zhongwencool** [comment]
I think It's better to use system lib or recon to fetch the metrics instead of observer_cli.
